### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by ghost** [jessica-suen/prj-rev-bwfs-dasmoto#5]
Satisfactory 💯 

You've done a really great job keeping your code organized and readable. You've also successfully reproduced the design specification we provided, so you've shown that you've understood the material so far.

Go back and add some alt attributes to your images. Your browser won't give you any "error" if you don't, but they're considered a standard if not an expectation in HTML5.

See if you can start getting familiar with some semantic HTML5 elements, like `header`, `footer`, `main`, `section`, etc. They'll make your code even more descriptive than you've already made it with your use of class names and organized structure.

**Comment by jessica-suen** [comment]
Oooh, great tips—didn't know about the alt attributes before this. 

Noted about being more descriptive with class names—that's good practice for later on down the road.

Thank you Steve!
